import { FileSystem, DeviceManager, os, path, process as proc } from "./vfsUtil.js";
export const fs=new FileSystem();
export const dev=new DeviceManager(fs);
proc.__setfs(fs);
export {process, os, path, retry} from "./vfsUtil.js";
export {LSFS} from "./fs/LSFS.js";
export {Buffer} from "buffer";
export {default as PathUtil} from "./fs/PathUtil.js";
//export {default as Content} from "./fs/Content.js";
export {getRootFS} from "./fs/index.js";
export const require=(module: string):any=>{
    if (module==="fs") return fs;
    if (module==="os") return os;
    if (module==="path") return path;
    return null;
};
export function fakeNodeEnvironment() {
    const g=globalThis as any;
    g.require=require;
    g.process=proc;
}
/*export default fs;
export function genExports() {
    let res="";
    for(let k in fs) {
        if (k==="default") continue;
        res+=`export const ${k}=fs.${k};\n`;
    }
    return res;
}*/
//---generated by genExports()----
